# Site settings
title: Austria
client:
  name: Austria
  link: ""
core-se-link: https://www.secretescapes.com/current-sales
description:

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/austria-collection" # the subpath of your site, e.g. /blog/
img:     "/austria-collection/_assets/img"
css:     "/austria-collection/_assets/css"
js:      "/austria-collection/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed